version: '3'

services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: "user"
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    networks:
      - tektek-net
  web-services:
    container_name: web
    build:
      context: .
      dockerfile: web-service/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks: 
      - tektek-net
  ml-services:
    container_name: ml
    build:
      context: .
      dockerfile: ml/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - tektek-net
networks:
  tektek-net:
    driver: bridge